// <auto-generated />
namespace IEP_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Invoicehasbeenchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Invoicehasbeenchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201608282047278_Invoice has been changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
