// <auto-generated />
namespace IEP_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedusertoauction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedusertoauction));
        
        string IMigrationMetadata.Id
        {
            get { return "201608292219397_Added user to auction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
